config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :movies, only: [:index] do
    resources :show_times, only: [:index] do
      resources :ticket_bookings, only: [:new, :create]
    end
  end
  get 'user_ticket_bookings', to: 'ticket_bookings#user_ticket_bookings'
  post 'ticket_bookings/cancel_multiple', to: 'ticket_bookings#cancel_multiple', as: 'cancel_multiple_ticket_bookings'
  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :genre, presence: true
  has_many :show_times
end

app/models/show_time.rb
class ShowTime < ApplicationRecord
  belongs_to :movie
  has_many :ticket_bookings
  validates :start_time, :end_time, :total_seats, presence: true

  def available_seats
    total_seats - ticket_bookings.count
  end

  def next_available_seats(num_seats)
    booked_seats = ticket_bookings.pluck(:seat_number).compact.sort
    available = []
    (1..total_seats).each do |seat|
      available << seat unless booked_seats.include?(seat)
      break if available.size >= num_seats
    end
    available
  end
end

app/models/ticket_booking.rb
class TicketBooking < ApplicationRecord
  attr_accessor :num_tickets

  belongs_to :show_time
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :ticket_bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    movies_path
  end
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/controllers/show_times_controller.rb
# frozen_string_literal: true

class ShowTimesController < ApplicationController
  before_action :set_movie

  def index
    @show_times = @movie.show_times
  end

  private

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end
end

app/controllers/ticket_bookings_controller.rb
# frozen_string_literal: true

class TicketBookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_show_time, except: %i[cancel_multiple user_ticket_bookings]

  def new
    @ticket_booking = @show_time.ticket_bookings.new
  end

  def create
    num_tickets = params[:ticket_booking][:num_tickets].to_i

    if num_tickets.positive? && @show_time.available_seats >= num_tickets
      seat_numbers = @show_time.next_available_seats(num_tickets)
      bookings = []

      seat_numbers.each do |seat_number|
        bookings << @show_time.ticket_bookings.new(ticket_booking_params.merge(seat_number: seat_number, user: current_user))
      end

      if bookings.all?(&:save)
        redirect_to movie_show_times_path(@movie), notice: "#{num_tickets} tickets booked successfully"
      else
        redirect_to movie_show_times_path(@movie), alert: 'Failed to book tickets'
      end
    else
      redirect_to movie_show_times_path(@movie), alert: 'Not enough available seats for the requested number of tickets'
    end
  end

  def cancel_multiple
    booking_ids = params[:booking_ids]
    if booking_ids.present?
      TicketBooking.where(id: booking_ids).destroy_all
      flash[:notice] = 'Selected bookings were successfully cancelled'
    else
      flash[:alert] = 'No bookings selected for cancellation'
    end
    redirect_to root_path
  end

  def user_ticket_bookings
    @user_bookings = current_user.ticket_bookings.includes(:show_time)
  end

  private

  def set_show_time
    @movie = Movie.find(params[:movie_id])
    @show_time = @movie.show_times.find(params[:show_time_id])
  end

  def ticket_booking_params
    params.require(:ticket_booking).permit(:num_tickets)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def book_tickets_link(show_time)
    if user_signed_in?
      link_to 'Book Tickets', new_movie_show_time_ticket_booking_path(show_time.movie, show_time), class: 'btn btn-primary'
    else
      link_to 'Book Tickets', new_user_session_path, class: 'btn btn-primary'
    end
  end

  def format_date(start_time, end_time)
    "#{start_time.strftime('%d/%m/%Y, %H:%M')} - #{end_time.strftime('%H:%M')}"
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/show_times_helper.rb
module ShowTimesHelper
end

app/helpers/ticket_bookings_helper.rb
module TicketBookingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookMyShowDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', 'custom' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container mt-5">
    <div class="row justify-content-end">
      <div class="col-auto button-container">
        <% if current_user.present? %>
          <%= button_to("Log Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger my-2') %>
          <%= link_to "Show Bookings", user_ticket_bookings_path, class: 'btn btn-primary' %>
        <% else %>
          <%= link_to "Sign Up / Sign In", new_user_session_path, class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
    <% flash.each do |key, message| %>
      <div class="alert mt-2 <%= key == 'notice' ? 'alert-success' : 'alert-danger' %>" role="alert">
        <%= message %>
      </div>
    <% end %>
  </div>
  <%= yield %>
</body>

</html>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= movie.title %></h5>
      <h6 class="card-subtitle mb-2 text-muted">Genre: <%= movie.genre %></h6>
      <p class="card-text"><%= movie.description %></p>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Movies</h1>

  <div id="movies">
    <% @movies.each do |movie| %>
      <div class="card mb-3">
        <%= render movie %>
        <div class="card-body">
          <p class="card-text">
            <% if movie.show_times.any? %>
              <%= link_to "Show Timings", movie_show_times_path(movie), class: 'btn btn-primary' %>
            <% else %>
              <span>No show time available</span>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/show_times/index.html.erb
<div class="container mt-5">

  <% @show_times.each do |show_time| %>
    <div id="<%= dom_id show_time %>" class="card mb-3">
      <div class="card-body">
        <h5 class="card-title">Movie time: <%= format_date(show_time.start_time, show_time.end_time) %></h5>
        <p class="card-text">Available seats: <%= show_time.available_seats %></p>
        <p class="card-text">Price: <%= show_time.price %></p>
        <p class="card-text">Movie: <%= show_time.movie_id %></p>
        <p>
          <%= book_tickets_link(show_time)%>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/ticket_bookings/_ticket_booking.html.erb
<div class="container mt-5">
  <% @ticket_bookings.each do |ticket_booking| %>
    <div id="<%= dom_id ticket_booking %>" class="card mb-3">
      <div class="card-body">
        <h5 class="card-title">Seat number: <%= ticket_booking.seat_number %></h5>
        <p class="card-text">Show time: <%= ticket_booking.show_time_id %></p>
        <p class="card-text">User: <%= ticket_booking.user_id %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/ticket_bookings/new.html.erb
<div class="container mt-5">
  <!-- New Ticket Booking Form -->
  <div class="card">
    <div class="card-body">
      <h1 class="card-title">Ticket Booking</h1>

      <%= form_with(model: [@movie, @show_time, @ticket_booking], url: movie_show_time_ticket_bookings_path(@movie, @show_time), method: :post) do |form| %>
        <% if @ticket_booking.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@ticket_booking.errors.count, "error") %> prohibited this ticket booking from being saved:</h2>

            <ul>
            <% @ticket_booking.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="card mb-4">
          <div class="card-body">
            <h2 class="card-title"><%= @movie.title %></h2>
            <h5 class="card-subtitle mb-2 text-muted"><%= @movie.genre %></h5>
            <p class="card-text"><%= @movie.description %></p>
          </div>
        </div>
        <div class="form-group">
          <%= form.label :number_of_tickets %>
          <%= form.number_field :num_tickets, class: "form-control" %>
        </div>

        <div class="form-actions mt-2">
          <%= form.submit "Book Tickets", class: "btn btn-primary" %>
          <%= link_to 'Back', movie_show_times_path(@movie), class: "btn btn-secondary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/ticket_bookings/user_ticket_bookings.html.erb
<div class="container mt-5">
  <h1>My Bookings</h1>

    <% if current_user.ticket_bookings.any? %>
      <%= form_tag(cancel_multiple_ticket_bookings_path, method: :post, data: { turbo: false }) do %>
        <% current_user.ticket_bookings.group_by { |booking| booking.show_time }.each do |show_time, bookings| %>
          <% if show_time == bookings.first.show_time %>
            <div class="card mb-3">
              <div class="card-header">
                <h4 class="card-title mb-0">
                  Movie: <%= show_time.movie&.title %> - Show Time: <%= format_date(show_time.start_time, show_time.end_time) %>
                </h4>
              </div>
              <div class="card-body">
                <% bookings.each do |booking| %>
                  <div class="form-check">
                    <%= check_box_tag 'booking_ids[]', booking.id, false, class: "form-check-input" %>
                    <label class="form-check-label"><strong>Seat Number:</strong> <%= booking.seat_number %></label>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
        <%= submit_tag 'Cancel Selected Bookings', class: "btn btn-danger my-2" %>
      <% end %>
    <% end %>

  <%= link_to 'back', movies_path, class: 'btn btn-primary' %>
</div>